### ISSUE TITLE
DUDE ANSWER

### ISSUE THREAD

**Issue by Blooket-dude** [shxrkyylol/blooket-hacks#2]
bro why did u copy my scripts

get rid of them or give me credits please

@shxrkyylol wait are you talking bout the .gitgore and the .license?

**Comment by Blooket-dude** [comment]
on my page

**Comment by Blooket-dude** [comment]
i kinda need to know so I can delete

**Comment by shxrkyylol** [comment]
@Blooket-dude I am talking about the https://github.com/Blooket-dude/blooket-hacks-1 github page.

**Comment by Blooket-dude** [comment]
@shxrkyylol I already fixed it

**Comment by colbymcdaniel** [comment]
hi
